name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Make binaries
      run: make
    - name: Prepare Artifacts
      run: mkdir artifact && mv pspdecrypt artifact/. && cp Readme.md artifact/.
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-binaries
        path: artifact
        
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
             install: >-
                base-devel
                git
                mingw-w64-x86_64-clang
                mingw-w64-x86_64-openssl
      - uses: actions/checkout@v4
      - name: Makes Binaries
        run: make EXTRA_FLAG=-static
      - name: Prepare Artifacts
        run: mkdir artifact && mv pspdecrypt artifact/. && cp Readme.md artifact/.
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-binaries
          path: artifact
        
  build-macos-x86:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
    - name: Make binaries
      run: |
        # export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/
        make CXX='clang++ -std=c++11'
    - name: Prepare Artifacts
      run: mkdir artifact && mv pspdecrypt artifact/. && cp Readme.md artifact/.
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-intel-binaries
        path: artifact

  build-macos-arm:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Make binaries
      run: |
        make CXX='clang++ -std=c++11'
    - name: Prepare Artifacts
      run: mkdir artifact && mv pspdecrypt artifact/. && cp Readme.md artifact/.
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-silicon-binary
        path: artifact
